name: build mediaProxy

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH Connection to Actions'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.23' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # 安装 Android SDK/NDK (gomobile 必需)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: r25c  # 推荐使用稳定版本[7](@ref)

      # 配置 Android 环境变量
      - name: Set Android environment variables
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV

      # 安装 gomobile 工具
      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init  # 初始化 gomobile 环境[1,2](@ref)
          go get golang.org/x/mobile/bind
          

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
          upx --version

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
          
      - name: SSH Connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
          
      - name: Build Go with UPX Compression
        run: |
          set +e
          # 定义目标平台数组
          platforms=(
            "linux/386" "linux/amd64" "linux/arm" "linux/arm64"
            "darwin/amd64" "darwin/arm64"
            "windows/386:.exe" "windows/amd64:.exe"
            "android/arm64" "android/arm"
          )

          # 遍历所有平台进行编译和压缩
          for platform in "${platforms[@]}"; do
            GOOS=${platform%/*}
            GOARCH=${platform#*/}
            CGO_ENABLED=0
            EXTENSION=""
            
            # 处理带扩展名的平台（如Windows）
            if [[ "$GOARCH" == *":"* ]]; then
              EXTENSION=${GOARCH#*:}
              GOARCH=${GOARCH%:*}
            fi
            
            # 针对 android 设置 CGO CC
            if [[ "$GOOS" == "android"]]; then
              # 针对 android/arm 设置 GOARM=7
              if [[ "$GOARCH" == "arm" ]]; then
                export GOARM=7
              fi
              CGO_ENABLED=1
              declare -A goarch2cc=( ["arm64"]="aarch64-linux-android32-clang" ["arm"]="armv7a-linux-androideabi32-clang" ["amd64"]="x86_64-linux-android32-clang" ["386"]="i686-linux-android32-clang"); 
              export CC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${goarch2cc[$GOARCH]}";
            fi 
            
            OUTPUT="mediaProxy-${GOOS}-${GOARCH}${EXTENSION}"
            
            echo "▶ 编译 $OUTPUT"
            CGO_ENABLED=$CGO_ENABLED GOOS=$GOOS GOARCH=$GOARCH \
              go build -trimpath -ldflags="-s -w -X main.Version=${{ github.sha }}" \
              -tags netgo -installsuffix netgo -o "$OUTPUT"
            
            echo "⚡ 压缩 $OUTPUT"
            upx --best --lzma "$OUTPUT" -o "${OUTPUT%.*}-compressed${EXTENSION}"
          done

          echo "FILESNAME=$PWD" >> $GITHUB_ENV
  
      # 新增的 gomobile 编译步骤
      - name: Build Android APK with gomobile
        run: |
          # 构建 Android APK
          gomobile bind -trimpath -ldflags "-s -w" -v -target=android/arm,android/arm64 -androidapi 21 -o mediaProxy.apk
          
          # 构建 Android 库 (AAR)
          gomobile bind -trimpath -ldflags "-s -w" -v -target=android/arm,android/arm64 -androidapi 21 -o mediaProxy.aar
          
          echo "✅ gomobile 构建完成"
          ls -lh mediaProxy.*

      - name: Bump Version and Push Tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Compressed Binaries to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          files: |
            *-compressed*
            mediaProxy.apk    # 添加 APK 文件
            mediaProxy.aar    # 添加 AAR 库文件
          draft: false
          prerelease: false
          body: |
            ### UPX压缩效果报告
            - 压缩算法：LZMA (--best模式)
            - 预期体积缩减：50%-70%
            - 启动延迟：增加约10-100ms解压时间
            
            ### gomobile 构建详情
            - Android 目标 API: 21[3](@ref)
            - 包含 APK 应用文件和 AAR 库文件[2,6](@ref)
            - 支持 ARM 和 ARM64 架构

      - name: Cleanup Old Artifacts
        run: |
          rm -f mediaProxy-*[!.][!c][!o][!m][!p][!r][!e][!s][!s][!e][!d]*

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3

      - name: Remove Old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
